version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./:/var/www
      - .docker/nginx:/etc/nginx/conf.d
    networks:
      - app-network
    depends_on:
      - backend
  backend:
    build:
      context: .docker/php
      dockerfile: dockerfile
    container_name: backend
    volumes:
      - ./:/var/www
      - .docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
      - postgres-network
      - redis-network
      - frontend-network
  redis:
    image: bitnami/redis:6.0
    container_name: redis
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - .docker/redis/data:/bitnami/redis/data
    environment:
      - PROTECTED_MODE=no
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - redis-network
    depends_on:
      - backend
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/postgres
    volumes:
       - .docker/postgres/data:/data/postgres
    ports:
      - 5432:${DB_PORT}
    networks:
      - postgres-network
    restart: unless-stopped
    depends_on:
      - backend
  frontend: 
    image: node:latest
    container_name: frontend
    working_dir: /var/app/
    entrypoint: bash -c "npm install && npm run dev"
    environment:
      DEV_PORT: ${FRONTEND_DEV_PORT:-8324}
      PREV_PORT: ${FRONTEND_PREVIEW_PORT:-8240}
    ports:
      - ${FRONTEND_DEV_PORT:-8324}:${FRONTEND_DEV_PORT:-8324}
      - ${FRONTEND_PREVIEW_PORT:-8240}:${FRONTEND_PREVIEW_PORT:-8240}
    volumes:
      - ./backend:/var/app
    networks:
      - frontend-network

networks:
  app-network:
  postgres-network:
  redis-network:
  frontend-network:

volumes:
  app-data:
